server:
  port: 8092

spring:
  application:
    name: opentms-exposure
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/opentms
    username: opentms
    password: opentms123

mybatis-plus:
  global-config:
    db-config:
      id-type: auto